file:
  upload:
    movie-type: .mp4
    # 设置pic的类型：所有的图片类型
    pic-type: .jpg|.jpeg|.png|.bmp|.gif|.ico|.tiff|.tif|.svg|.webp

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 3GB
      max-request-size: 3GB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: USERNAME
    password: PASSWORD
  redis:
    client-name: project
    host: 127.0.0.1
    port: 6379
    password: 411326
    # 连接时间
    timeout: 10000
    # 连接池配置
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  mvc:
    view:
      prefix:

# mybatis-plus的配置
mybatis-plus:
  # 实体类所在的包
    typeAliasesPackage: com.guico.moviemanagesystembackend.entity
    #输出sql语句
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sa-token:
  # token名称
  token-name: satoken
  # token有效时间（单位：秒）
  activity-timeout: 1800000
  # 是否允许多人同时登录
  is-concurrent: true
  # token风格
  token-style: uuid
  # 是否输出token日志
  is-log: true
  # sso配置
  sso:
    auth-url: http://localhost:8080/sa-token-auth
    slo-url: http://localhost:8080/sa-token-logout
server:
  port: 28545
# 邮箱配置
mail:
  host: "smtp.163.com"
  from: "EMAIL@163.com"
  token: "PASSWORD"
  port: 465