
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.33.210.228:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: project
    password: wwNBDPmRWxi8L82K
  redis:
    client-name: project
    host: 101.33.210.228
    port: 6379
    password: 411326
# mybatis-plus的配置
mybatis-plus:
  # 实体类所在的包
    typeAliasesPackage: com.guico.moviemanagesystembackend.entity
sa-token:
  # token名称
  token-name: satoken
  # token有效时间（单位：秒）
  activity-timeout: 1800000
  # 是否允许多人同时登录
  is-concurrent: false
  # token风格
  token-style: uuid
  # 是否输出token日志
  is-log: true
server:
  port: 8901